---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: petclinic-deployed-notification
  namespace: petclinic
  labels:
    app.kubernetes.io/name: petclinic
    app: petclinic
spec:
  job_template_name: Demo Job Template
  extra_vars:
    name: petclinic
    deployed: true